### ISSUE TITLE
Update the GitHub organization to use the NullpoMino logo

### ISSUE THREAD

**Issue by rogersachan** [nullpomino/nullpomino#57]
![44752265](https://user-images.githubusercontent.com/7173984/62340042-259e0b80-b4ac-11e9-8842-49672ccac823.png)

This image is included in the game files and was used on the NullpoMino facebook wall. I think this would be nice for whenever the repo is linked somewhere so the logo shows instead of the gravatar generated image.

**Comment by TSTman** [comment]
Dang that is a nice icon. Cropped and added as the GitHub organization's logo.
